- name: app setup
  import_role:
    name: common
    tasks_from: app-setup 

- name: java setup
  import_role:
    name: common
    tasks_from: java

- name: mysql setup
  import_role:
    name: common
    tasks_from: mysql-setup

- name: service start
  import_role:
    name: common
    tasks_from: systemd