- name: app setup
  import_role:
    name: common
    tasks_from: app-setup 

- name: python setup
  import_role:
    name: common
    tasks_from: python



- name: service start
  import_role:
    name: common
    tasks_from: systemd