- name: app setup
  import_role:
    name: common
    tasks_from: app-setup 

- name: nodejs setup
  import_role:
    name: common
    tasks_from: nodejs

- name: mongodb setup
  import_role:
    name: common
    tasks_from: mongodb-setup
