- name: catalogue
  hosts: catalogue
  become: true
  tasks:
    - name: disable latest nodejs and enable nodejs 18 
      ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y

    - name: install node js
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create roboshop user
      ansible.builtin.user: 
        name: roboshop      

    - name: create app directory 
      ansible.builtin.file:
        path: /app 
        state: directory 

    - name: download catalogue code
      ansible.builtin.get_url: 
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: unzip catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app 
        remote_src: yes

    - name: install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy catalogue ervice
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: daemon reload and start catalogue 
      ansible.builtin.systemd:
        daemon-reload: true

    - name: copy mongo repo 
      ansible.builtin.copy:
        src: cmongo.repo  
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: get categories product count
      ansible.builtin.command: mongo --host mongodb.aws-devops.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count 

    - name: load catalogue data
      ansible.builtin.command: mongo --host mongodb.aws-devops.online < /app/schema/catalogue.js
      when: product_count.stdout == "0"


    - name: start and enable catalogue
      ansible.builtin.service:
       name: catalogue
       state: restarted
       enabled: yes







