- name: mysql
  hosts: mysql
  become: true
  tasks:
    - name: disable mysql module
      ansible.builtin.command: dnf module disable mysql -y

    - name: copy mysql.repo to yum repos 
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: install mysql
      ansible.builtin.package:
        name: mysql-community-server  
        state: present
    - name: start and enable mysql
      ansible.builtin.service:
        name: mysqld
        state: started 
        enabled: true
    - name: set root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1         