- name: copy mongo repo 
  ansible.builtin.copy:
    src: mongo.repo  
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get catalogue entries count
  ansible.builtin.command: mongo --host mongodb.aws-devops.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count 
  when: component == "catalogue"

- name: get user entries count
  ansible.builtin.command: mongo --host mongodb.aws-devops.online --quiet --eval 'db = db.getSiblingDB("user"); db.products.count()'
  register: users_count 
  when: component == "user"  

- name: "load {{component}} data"
  ansible.builtin.command: "mongo --host mongodb.aws-devops.online < /app/schema/{{component}}.js"
  when: products_count.stdout == "0" And component == "catalogue"

- name: "load {{component}} data"
  ansible.builtin.command: "mongo --host mongodb.aws-devops.online < /app/schema/{{component}}.js"
  when: users_count.stdout == "0"  And component == "user"