# - name: copy "{{component}} service"
#   ansible.builtin.copy:
#     src: "{{component}}.service"
#     dest: "/etc/systemd/system/{{component}}.service"

- name: copy "{{component}} service"
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"    

- name: "daemon reload and start {{component}}" 
  ansible.builtin.systemd:
    daemon-reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes